### ISSUE TITLE
Adding support for extra arguments to override the estimator yaml config in a kubeflow pipeline

### ISSUE THREAD

**Issue by AdamPalmarUnity** [Unity-Technologies/datasetinsights#54]
/kind feature

**Why you need this feature:**

In order to avoid rebuilding the docker container to change the estimator yaml configuration. Allowing the user to provide extra arguments with the cli command for evaluate and train.  

**Describe the solution you'd like:**
For the estimator configuration 

```
estimator: FasterRCNN
backbone: resnet50
num_classes: 64
task: object_detection
train:
  dataset:
    name: SynDetection2D
    args:
      run_execution_id: zMvGEV0
      version: 0.0.1
      def_id: c31620e3-55ff-4af6-ae86-884aa0daa9b2
      random_seed: 47
      split: train
  batch_size: 4
  accumulation_steps: 8
  epochs: 50
  log_frequency: 10
val:
  dataset:
    name: SynDetection2D
    args:
      run_execution_id: zMvGEV0
      version: 0.0.1
      def_id: c31620e3-55ff-4af6-ae86-884aa0daa9b2
      random_seed: 47
      split: val
  batch_size: 4
test:
  dataset:
    name: GroceriesReal
    args:
      version: v3
      split: test
  batch_size: 4
metrics:
  mAP:
    name: MeanAveragePrecisionAverageOverIOU
  mAPIOU50:
    name: MeanAveragePrecisionIOU50
  mAR:
    name: MeanAverageRecallAverageOverIOU
  APIOU50:
    name: AveragePrecisionIOU50
optimizer:
  name: Adam
  args:
    lr: 2.0e-4
pretrained: False
pretrained_backbone: True
val_interval: 1
```

Being able to override the estimator config the following way.

The example below will override the optimizer.args.lr value and the number of train.epochs. 
`datasetinsights train --config=path/to/config --train-data=path optimizer.args.lr 0.00005 train.epochs 100   `

This will design will allow the cli to take extra arguments that will override the values in the config file. 

The proposed code change to the cli is the evaluate command as an example:

```

def cli(
    config,
    checkpoint_file,
    test_data,
    tb_log_dir,
    workers,
    kfp_metrics_dir,
    kfp_metrics_filename,
    no_cuda,
):
    ctx = click.get_current_context()
    logger.debug(f"Called evaluate command with parameters: {ctx.params}")
    logger.debug(f"Override estimator config with args: {ctx.args}")
    config = CN.load_cfg(open(config, "r"))

   ------ new code --------
    if len(ctx.args) == 1:
        config.merge_from_list(ctx.args[0].split(" "))
    else:
        config.merge_from_list(ctx.args)
   ---------------------------
    estimator = create_estimator(
        config=config,
        name=config.estimator,
        checkpoint_file=checkpoint_file,
        tb_log_dir=tb_log_dir,
        workers=workers,
        kfp_metrics_dir=kfp_metrics_dir,
        kfp_metrics_filename=kfp_metrics_filename,
        no_cuda=no_cuda,
    )

    estimator.evaluate(test_data=test_data)

```
There are the following reasons for the two cases:
1. Handles kubeflow pipeline conversion of run parameters to strings 
2. Handles when the cli is invoked directly.
